name: Exemplo Simples

on:
  workflow_dispatch: # Permite executar o workflow manualmente

jobs:
  exemplo:
    runs-on: ubuntu-latest # Ambiente de execução

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3 # Faz o checkout do repositório

      - name: Imprime mensagem Olá
        run: echo "Olá"

      - name: Imprime mensagem Tchau
        run: echo "Tchau"
